---
kind: Template
apiVersion: v1
metadata:
  name: dacs
  creationTimestamp: null
  annotations:
    openshift.io/display-name: DACS
    description: Trabalho de DACS em kubernetes
    iconClass: icon-php
    tags: php,nginx,database,postgresql
    template.openshift.io/long-description: Este template de serviços do trabalho de DACS.
    template.openshift.io/provider-display-name: Eduardo Klosowski
    template.openshift.io/documentation-url: https://github.com/eduardo-univille/trabalho-dacs
message: O serviço ${SERVICE_NAME} foi criado.
labels:
  template: dacs-template
objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      name: ${SERVICE_NAME}-pg
    stringData:
      database-user: ${POSTGRESQL_USER}
      database-password: ${POSTGRESQL_PASSWORD}
  - kind: Service
    apiVersion: v1
    metadata:
      name: ${SERVICE_NAME}-pg
      creationTimestamp: null
    spec:
      ports:
        - name: postgresql
          protocol: TCP
          port: 5432
          targetPort: 5432
          nodePort: 0
      selector:
        name: ${SERVICE_NAME}-pg
      type: ClusterIP
      sessionAffinity: None
    status:
      loadBalancer:
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${SERVICE_NAME}-pg
      creationTimestamp: null
    spec:
      strategy:
        type: Recreate
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - postgresql
            from:
              kind: ImageStreamTag
              name: postgresql:9.5
              namespace: openshift
            lastTriggeredImage: ''
        - type: ConfigChange
      replicas: 1
      selector:
        name: ${SERVICE_NAME}-pg
      template:
        metadata:
          creationTimestamp: null
          labels:
            name: ${SERVICE_NAME}-pg
        spec:
          containers:
            - name: postgresql
              image: ' '
              ports:
                - containerPort: 5432
                  protocol: TCP
              readinessProbe:
                timeoutSeconds: 1
                initialDelaySeconds: 5
                exec:
                  command: ['/bin/sh', '-i', '-c', 'psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d $POSTGRESQL_DATABASE -c "SELECT 1"']
              livenessProbe:
                timeoutSeconds: 1
                initialDelaySeconds: 30
                tcpSocket:
                  port: 5432
              env:
                - name: POSTGRESQL_USER
                  valueFrom:
                    secretKeyRef:
                      name: ${SERVICE_NAME}-pg
                      key: database-user
                - name: POSTGRESQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${SERVICE_NAME}-pg
                      key: database-password
                - name: POSTGRESQL_DATABASE
                  value: ${POSTGRESQL_DATABASE}
              volumeMounts:
                - name: ${SERVICE_NAME}-data
                  mountPath: /var/lib/pgsql/data
              terminationMessagePath: /dev/termination-log
              imagePullPolicy: IfNotPresent
              capabilities:
              securityContext:
                capabilities:
                privileged: false
          volumes:
            - name: ${SERVICE_NAME}-data
              emptyDir:
                medium: ''
          restartPolicy: Always
          dnsPolicy: ClusterFirst
    status:
parameters:
  - name: SERVICE_NAME
    displayName: Nome do Serviço
    description: Nome do serviço OpenShift.
    value: 'dacs'
    required: true
  - name: POSTGRESQL_USER
    displayName: Usuário do PostgreSQL
    description: Usuário do PostgreSQL para acessar o banco de dados.
    generate: expression
    from: 'user[A-Z0-9]{3}'
    required: true
  - name: POSTGRESQL_PASSWORD
    displayName: Senha do PostgreSQL
    description: Senha do usuário do PostgreSQL para acessar o banco de dados.
    generate: expression
    from: '[a-zA-Z0-9]{16}'
    required: true
  - name: POSTGRESQL_DATABASE
    displayName: Nome do banco
    description: Nome do banco de dados do PostgreSQL.
    value: dacs
    required: true
