version: '2.1'
services:
  pg:
    image: postgres:alpine
    environment:
      POSTGRES_DB: dacs
  php:
    build: .
    environment:
      DSN: pgsql:host=pg;port=5432;dbname=dacs;user=postgres
    depends_on:
      - pg
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    ports:
      - "8000:80"
    depends_on:
      - php
